config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations",
    passwords: "admins/passwords",
  }

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
  }

  scope module: :user do
    get "/" => "homes#top"
    resources :magazines, only: [:index, :show]
    resources :users, only: [:show, :edit, :update] do
      collection do
        patch 'withdraw'
      end
    end
    
    resources :theaters, only: [:index, :show] do
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      collection do
      get 'search'
      end
    end
  end
  
  #管理者側ルート
  namespace :admin do
    resources :theaters
    resources :magazines
  end
  
  #お問い合わせルート
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  def create
    theater = Theater.find(params[:theater_id])
    comment = current_user.comments.new(comment_params)
    comment.theater_id = theater.id
    comment.save
    redirect_to theater_path(theater.id)
  end

  def destroy
    Comment.find_by(id: params[:id], theater_id: params[:theater_id]).destroy
    redirect_to theaters_path(params[:theater_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :clean)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  def create
    theater = Theater.find(params[:theater_id])
    favorite = current_user.favorites.new(theater_id: theater.id)
    favorite.save
    redirect_to theater_path(theater)
  end

  def destroy
    theater = Theater.find(params[:theater_id])
    favorite = current_user.favorites.find_by(theater_id: theater.id)
    favorite.destroy
    redirect_to theater_path(theater)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  
  def top
    @all_ranks = Theater.find(Favorite.group(:theater_id).order('count(theater_id) desc').limit(3).pluck(:theater_id))
  end
end

app/controllers/user/magazines_controller.rb
class User::MagazinesController < ApplicationController
  def index
    @magazines = Magazine.all
  end

  def show
    @magazine = Magazine.find(params[:id])
  end
end

app/controllers/user/theaters_controller.rb
class User::TheatersController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def index
    @theaters = Theater.all.page(params[:page]).per(10)
  end

  def show
    if user_signed_in?
    @theater = Theater.find(params[:id])
    @comment = Comment.new
    else
      redirect_to new_user_session_path
    end
  end

  def search
    @results = @q.result.page(params[:page]).per(10)
  end

  private
  def set_q
    @q = Theater.ransack(params[:q])
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if
      @user.update(update_params)
      redirect_to user_path(@user.id), notice: 'お客様情報を更新しました。'
    else
      render :edit
    end
  end

  def withdraw
    @user = current_user.destroy
    reset_session
    redirect_to "/"
  end

  private
  def update_params
    params.require(:user).permit(:name, :email, :phone_number, :image)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :configure_permitted_parameters , if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :encrypted_password])
  end
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters , if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password])
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_permitted_parameters , if: :devise_controller?
  #ログイン後トップページに
  def after_sign_in_path_for(resource)
    theaters_path(resource)
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password])
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/theaters_helper.rb
module User::TheatersHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/users/edit.html.erb
<div class="container container-m">
 <div class="card w-200 mx-auto mt-4 shadow-lg">
  <div class="card-body">
   <div class="row">
    <div class="col-12">
     <h2 class="card-title">登録情報を編集</h2>
      <table class="table">
       <tbody>
        <%= form_with model: @user, local:true do |f| %>
         <tr>
          <div class="form">
          <th scope="col-2">氏名</th>
          <td>
           <%= f.text_field :name, autofocus: true %>
          </td>
          </div>
         </tr>
         <tr>
          <div class="form">
          <th scope="col-2">電話番号</th>
          <td><%= f.text_field :phone_number, autofocus: true %></td>
         </tr>
          </div>
         <tr>
          <div class="form">
          <th scope="col-2">メールアドレス</th>
          <td><%= f.text_field :email, autofocus: true %></td>
         </tr>
         </div>
         <tr>
          <div class="form">
          <th scope="col-2">ユーザー画像</th>
          <td><%= f.attachment_field :image %></td>
         </tr>
         </div>
         <tr>
          <div class="action">
          <td>
           <%= f.submit "編集内容を保存",class: "btn btn-success" %>
           <%= link_to "退会する", withdraw_users_path, method: :patch, class: "btn btn-danger", data: { confirm: '本当に退会しますか?'} %>
          </td>
          </div>
         </tr>
        <% end %>
       </tbody>
      </table>
    </div>
   </div>
  </div>
 </div>
</div>

app/views/user/users/show.html.erb
<div class="container container-m">
  <div class="card w-200 mx-auto mt-4 shadow-lg">
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <p><%= attachment_image_tag @user, :image, :fill, 100, 100, class:"rounded-circle" %></p>
        </div>
        <div class="col-6">
        <h2 class="card-title m-2"><%= @user.name %></h2>
        <table class="table">
          <tbody>
            <tr>
              <th scope="row">メールアドレス</th>
              <td><%= @user.email %></td>
            </tr>
            <tr>
              <th scope="row">電話番号</th>
              <td><%= @user.phone_number %></td>
            </tr>
          </tbody>
        </table>
        </div>
        <%= link_to "編集する", edit_user_path(@user) %>
        </div>
      </div>
    </div>
  </div>
<div class="container container-m">
<h1 class="m-4">コメント一覧</h1>  
<% @user.comments.each do |comments| %>
  <div class="card w-200 mx-auto mt-4 shadow-lg">
    <div class="card-body">
        <div class="row">
         <div class="col-10">
          <h3>劇場名
          <%= link_to theater_path(comments.theater.id) do %>
          <%= comments.theater.name %>
          <% end %>
          </h3>
          <p>投稿日 <%= comments.created_at.strftime('%Y/%m/%d') %>
          </p>
          <p>コメント 
          <%= comments.comment %>
          </p>
          <p>
            <div class="relative-comment-evaluation">
            <span>評価：</span>
            <span id="star-rate-<%= comments.id %>"></span>
            <script>
            $('#star-rate-<%= comments.id %>').raty({
            size: 36,
            starOff: "<%= asset_path('star-off.png') %>",
            starOn: "<%= asset_path('star-on.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            half: true,
            readOnly: true,
            score: <%= comments.clean %>,
            });
            </script>
            <%= comments.clean %>
            </div>
          </p>
         </div>
         <div class="col-2">
          <p>
            <% if comments.user == current_user %>
              <div class="comment-delete">
                <%= link_to "削除", theater_comment_path(comments.theater, comments), method: :delete, class:"btn btn-outline-danger" %>
              </div>
            <% end %>
          </p>
         </div>
        </div>
    </div>
  </div>
<% end %>
</div>
<div class="container container-m">
<h1 class="m-4">いいね一覧</h1>  
<% @user.favorites.each do |favorites| %>
  <div class="card w-200 mx-auto mt-4 shadow-lg">
    <div class="card-body">
      <div class="row">
        <div class="col-4">
          <h3>劇場名
              <%= link_to theater_path(favorites.theater.id) do %>
              <%= favorites.theater.name %>
              <% end %>
            </h3>
        </div>
        <div class="col-2">
          <p>登録日
            <%= favorites.created_at.strftime('%Y/%m/%d') %>
          </p>
        </div>
        <div class="col-2">
          <h1 class="badge badge-danger">
            いいね ♥ <%= favorites.theater.favorites.count %>件
          </h1>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>