config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations",
    passwords: "admins/passwords",
  }

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
  }

  scope module: :user do
    get "/" => "homes#top"
    resources :magazines, only: [:index, :show]
    resources :users, only: [:show, :edit, :update] do
      collection do
        patch 'withdraw'
      end
    end
    
    resources :theaters, only: [:index, :show] do
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      collection do
      get 'search'
      end
    end
  end
  
  #管理者側ルート
  namespace :admin do
    resources :theaters
    resources :magazines
  end
  
  #お問い合わせルート
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :theater
  
  validates :clean, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  
  validates :comment, presence: true
  validates :clean, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :theater
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/magazine.rb
class Magazine < ApplicationRecord
  attachment :image
  
  validates :title, :presence => {:message => 'タイトルを入力してください'}
  validates :content, :presence => {:message => '内容を入力してください'}
  validates :image, :presence => {:message => '写真を挿入してください'}
end

app/models/theater.rb
class Theater < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  enum prefecture:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def index
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when User
      theaters_path
    when Admin
      admin_theaters_path
    end
  end
  
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))    
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  
  def top
    @all_ranks = Theater.find(Favorite.group(:theater_id).order('count(theater_id) desc').limit(3).pluck(:theater_id))
  end
end

app/helpers/admin/magazines_helper.rb
module Admin::MagazinesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/theaters_helper.rb
module Admin::TheatersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/theaters_helper.rb
module User::TheatersHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/inquiry/confirm.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>

<%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :name %>
        <%= @inquiry.name %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @inquiry.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@inquiry.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'btn btn-primary' %>
<% end %>

app/views/inquiry/index.html.erb
<div class="container container-m">
  <div class="card w-200 mx-auto mt-4 shadow-lg">
    <div class="card-body">
      <div class="row">
        <div class="col-12">
         <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
          <div class="page-header">
           <h1>お問い合わせ</h1>
          </div>
          <% if @inquiry.errors.any? %>
           <div class="alert alert-danger" role="alert">
            <strong>入力内容にエラーがあります</strong>
            <ul>
             <% @inquiry.errors.each do |attr, msg| %>
              <li><%= msg %></li>
             <% end %>
            </ul>
           </div>
          <% end %>
          <table class="table">
           <tr>
            <th>名前<span class="text-danger">（必須）</span></th>
            <td><%= f.text_field :name, class:"form-control" %></td>
           </tr>
           <tr>
            <th>メールアドレス<span class="text-danger">（必須）</span></th>
            <td><%= f.text_field :email, class:"form-control" %></td>
           </tr>
           <tr>
            <th>お問い合わせ内容</th>
            <td><%= f.text_area :message, class:"form-control" %></td>
           </tr>
          </table>
          <%= f.submit '確認', class: 'btn btn-primary' %>
         <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/inquiry/thanks.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
<p>
  お問い合わせいただきありがとうございました。
</p>