config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations",
    passwords: "admins/passwords",
  }

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
  }

  scope module: :user do
    get "/" => "homes#top"
    resources :magazines, only: [:index, :show]
    resources :users, only: [:show, :edit, :update] do
      collection do
        patch 'withdraw'
      end
    end
    
    resources :theaters, only: [:index, :show] do
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      collection do
      get 'search'
      end
    end
  end
  
  #管理者側ルート
  namespace :admin do
    resources :theaters
    resources :magazines
  end
  
  #お問い合わせルート
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :theater
  
  validates :clean, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  
  validates :comment, presence: true
  validates :clean, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :theater
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/magazine.rb
class Magazine < ApplicationRecord
  attachment :image
  
  validates :title, :presence => {:message => 'タイトルを入力してください'}
  validates :content, :presence => {:message => '内容を入力してください'}
  validates :image, :presence => {:message => '写真を挿入してください'}
end

app/models/theater.rb
class Theater < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  enum prefecture:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when User
      theaters_path
    when Admin
      admin_theaters_path
    end
  end
  
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))    
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/theaters_helper.rb
module Admin::TheatersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/theaters_helper.rb
module User::TheatersHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>
            CopyRight ©Cinema Village <%= link_to "お問い合わせ", inquiry_path %>
            </p>
          </div>
        </div>
      </div>
    </footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
 <nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
   <div class="row">
    <div class="col-12">
     <h2><i class="fas fa-film"></i>
      <%= link_to "Cinema Village", "/", class:"text-dark" %>
     </h2>
    </div>
    <div class="col-12">
      <ul class="navbar-nav mr-auto">
       <% if user_signed_in? %>
        <li class="nav-item active"><%= link_to "マイページ", user_path(current_user), class: "nav-link" %></li>
        <li class="nav-item active"><%= link_to "劇場一覧", theaters_path, class: "nav-link" %></li>
        <li class="nav-item active"><%= link_to "マガジン", magazines_path, class: "nav-link" %></li>
        <li class="nav-item active"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
       <% elsif admin_signed_in? %>
        <li class="nav-item active"><%= link_to "劇場一覧", admin_theaters_path, class: "nav-link" %></li>
        <li class="nav-item active"><%= link_to "マガジン", admin_magazines_path, class: "nav-link" %></li>
        <li class="nav-item active"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %></li>
       <% else %>
        <li class="nav-item active"><%= link_to "新規登録", new_user_registration_path, class: "nav-link" %></li>
        <li class="nav-item active"><%= link_to "ログイン", new_user_session_path, class: "nav-link" %></li>
        <li class="nav-item active"><%= link_to "管理者ログイン", new_admin_session_path, class: "nav-link" %></li>
       <% end %>
      </ul>
    </div>
   </div>
  </div>
 </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CinemaVillege</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>