config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    registrations: "admins/registrations",
    passwords: "admins/passwords",
  }

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
  }

  scope module: :user do
    get "/" => "homes#top"
    resources :magazines, only: [:index, :show]
    resources :users, only: [:show, :edit, :update] do
      collection do
        patch 'withdraw'
      end
    end
    
    resources :theaters, only: [:index, :show] do
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      collection do
      get 'search'
      end
    end
  end
  
  #管理者側ルート
  namespace :admin do
    resources :theaters
    resources :magazines
  end
  
  #お問い合わせルート
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :theater
  
  validates :clean, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  
  validates :comment, presence: true
  validates :clean, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :theater
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/magazine.rb
class Magazine < ApplicationRecord
  attachment :image
  
  validates :title, :presence => {:message => 'タイトルを入力してください'}
  validates :content, :presence => {:message => '内容を入力してください'}
  validates :image, :presence => {:message => '写真を挿入してください'}
end

app/models/theater.rb
class Theater < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  enum prefecture:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def index
  end
  
end

app/controllers/admin/theaters_controller.rb
class Admin::TheatersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @theaters = Theater.all.page(params[:page]).per(10)
  end

  def show
    @theater = Theater.find(params[:id])
  end

  def new
    @theater = Theater.new
  end

  def create
    @theater = Theater.new(theater_params)
    if
      @theater.save
      flash[:notice] = "登録しました"
      redirect_to admin_theater_path(@theater.id)
    else
      render :new
    end
  end

  def edit
    @theater = Theater.find(params[:id])

  end

  def update
    @theater = Theater.find(params[:id])
    if
      @theater.update(theater_params)
      flash[:success] = "内容をを変更しました"
      redirect_to admin_theater_path(@theater.id)
    else
      render :edit
    end
  end

  def destroy
    @theater = Theater.find(params[:id])
    @theater.destroy
    redirect_to admin_theaters_path
  end

  private
  def theater_params
    params.require(:theater).permit(:name, :introduction, :address, :access, :parking, :phone_number, :url, :image, :prefecture)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when User
      theaters_path
    when Admin
      admin_theaters_path
    end
  end
  
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))    
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  
  def top
    @all_ranks = Theater.find(Favorite.group(:theater_id).order('count(theater_id) desc').limit(3).pluck(:theater_id))
  end
end

app/controllers/user/theaters_controller.rb
class User::TheatersController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def index
    @theaters = Theater.all.page(params[:page]).per(10)
  end

  def show
    if user_signed_in?
    @theater = Theater.find(params[:id])
    @comment = Comment.new
    else
      redirect_to new_user_session_path
    end
  end

  def search
    @results = @q.result.page(params[:page]).per(10)
  end

  private
  def set_q
    @q = Theater.ransack(params[:q])
  end
end

app/helpers/admin/magazines_helper.rb
module Admin::MagazinesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/theaters_helper.rb
module Admin::TheatersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/theaters_helper.rb
module User::TheatersHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/theaters/edit.html.erb
<div class="container container-m">
 <div class="card w-200 mx-auto mt-4 shadow-lg">
  <div class="card-body">
   <div class="row">
    <div class="col-12">
     <h2 class="card-title">登録情報を編集</h2>
      <table class="table">
       <tbody>
        <%= form_with model:[:admin, @theater], local:true do |f| %>
          <tr>
            <th scope="col-2">劇場名</th>
            <td>
            <%= f.text_field :name %>
            </td>
          </tr>
          <tr>
            <th scope="col-2">説明</th>
            <td><%= f.text_field :introduction, class:"form-control" %></td>
         </tr>
         <tr>
          <th scope="col-2">都道府県</th>
          <td><%= f.select :prefecture, Theater.prefectures.keys, {} %></td>
         </tr>
         <tr>
          <th scope="col-2">住所</th>
          <td><%= f.text_field :address %></td>
         </tr>
         <tr>
          <th scope="col-2">アクセス</th>
          <td><%= f.text_field :access %></td>
         </tr>
         <tr>
          <th scope="col-2">駐車場</th>
          <td><%= f.text_field :parking %></td>
         </tr>
         <tr>
          <th scope="col-2">電話番号</th>
          <td><%= f.text_field :phone_number %></td>
         </tr>
         <tr>
          <th scope="col-2">ホームページ</th>
          <td><%= f.text_field :url %></td>
         </tr>
         <tr>
          <th scope="col-2">施設写真</th>
          <td><%= f.attachment_field :image , class: "form-control-file image" %></td>
         </tr>
         <tr>
          <td><%= f.submit "編集内容を保存", class: "btn btn-success" %></td>
         </tr>
         <% end %>
        </tbody>
      </table>
    </div>
   </div>
  </div>
 </div>
</div>

app/views/admin/theaters/index.html.erb
<div class="container container-fluid">
 <div class="row mx-auto mt-4">
   <div class="col-5">
   <h2>劇場一覧 管理者側</h2>
   </div>
   <div class="col-5">
    <%= link_to new_admin_theater_path, data: {"turbolinks" => false}, class: "btn btn-warning pull-right" do %>
    <i class="fas fa-plus"></i>
    新規劇場登録
    <% end %>
   </div>
 </div>
</div>

 <div class="container container-fluid">
  <% @theaters.each do |theaters| %>
    <div class="card w-200 mx-auto mt-4 shadow-lg">
     <div class="card-body">
      <div class="row">
       <div class="col-4">
        <%= attachment_image_tag theaters, :image, size: "270x190", fallback: "no_image.jpg" %>
       </div>
       <div class="col-8">
        <h5 class="card-title"><%= theaters.id %></h5>
        <%= link_to admin_theater_path(theaters.id) do %>
        <h5 class="card-title"><%= theaters.name %></h5>
        <% end %>
        <p class="card-text text-dark"><%= theaters.introduction %></p>
        <p class="card-text text-dark"><%= theaters.prefecture %></p>
        <p><i class="far fa-comment-alt"></i> <%= theaters.comments.count %></p>
        <% @average = 0 %>
        <% theaters.comments.each do |comment| %>
        <% @average += (comment.clean / theaters.comments.count ) %>
        <% end %>
        <p><i class="far fa-star"></i> <%= @average.round(1) %></p>
       </div>
     </div>
    </div>
   </div>
 <% end %>
</div>
<div class="container">
 <div class="row">
  <div class="mx-auto m-3">
   <%= paginate @theaters %>
  </div>
 </div>
</div>

app/views/admin/theaters/new.html.erb
<div class="container container-m">
 <div class="card w-200 mx-auto mt-4 shadow-lg">
  <div class="card-body">
   <div class="row">
    <div class="col-12">
     <h2 class="card-title">劇場投稿</h2>
      <table class="table">
       <tbody>
        <%= form_with model:[:admin,@theater], method: :post, local:true do |f| %>
          <tr>
            <th scope="col-2">劇場名</th>
            <td>
            <%= f.text_field :name %>
            </td>
          </tr>
          <tr>
            <th scope="col-2">説明</th>
            <td><%= f.text_field :introduction, class:"form-control" %></td>
         </tr>
         <tr>
          <th scope="col-2">都道府県</th>
          <td><%= f.select :prefecture, Theater.prefectures.keys, {} %></td>
         </tr>
         <tr>
          <th scope="col-2">住所</th>
          <td><%= f.text_field :address %></td>
         </tr>
         <tr>
          <th scope="col-2">アクセス</th>
          <td><%= f.text_field :access %></td>
         </tr>
         <tr>
          <th scope="col-2">駐車場</th>
          <td><%= f.text_field :parking %></td>
         </tr>
         <tr>
          <th scope="col-2">電話番号</th>
          <td><%= f.text_field :phone_number %></td>
         </tr>
         <tr>
          <th scope="col-2">ホームページ</th>
          <td><%= f.text_field :url %></td>
         </tr>
         <tr>
          <th scope="col-2">施設写真</th>
          <td><%= f.attachment_field :image %></td>
         </tr>
         <tr>
          <td><%= f.submit "新規登録", class: "btn btn-primary btn-lg pull-right" %></td>
         </tr>
         <% end %>
        </tbody>
      </table>
    </div>
   </div>
  </div>
 </div>
</div>

app/views/admin/theaters/show.html.erb
<div class="container container-m">
  <div class="card w-200 mx-auto mt-4 shadow-lg">
    <div class="card-body">
      <div class="row">
        <div class="col-12">
        <h2 class="card-title m-2"><%= @theater.name %></h2>
        </div>
      </div>
      <div class="row">
        <div class="col-9">
          <div class="card-text m-4">
            <p><%= @theater.introduction %></p>
            <p><%= @theater.prefecture %></p>
            <p>投稿日時：<%= @theater.created_at.strftime('%Y/%m/%d') %></p>
            <p>コメント件数：<%= @theater.comments.count %></p>
            <% @average = 0 %>
            <% @theater.comments.each do |comment| %>
              <% @average += (comment.clean / @theater.comments.count ) %>
            <% end %>
            <p>評価 <%= @average.round(1) %>
            <span id="star-rate-<%= @average.to_i %>"></span>
            <script>
              $('#star-rate-<%= @average.to_i %>').raty({
              size: 36,
              starOff: "<%= asset_path('star-off.png') %>",
              starOn: "<%= asset_path('star-on.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              half: true,
              readOnly: true,
              score: <%= @average %>,
              });
            </script>
            </p>
          </div>
        </div>
          <div class="col-2">
            <p class="badge badge-danger">いいね ♥ <%= @theater.favorites.count %>件</p>
            <p><%= link_to "編集", edit_admin_theater_path(@theater), class: "btn btn-sm btn-success" %></p>
            <p><%= link_to "削除", admin_theater_path(@theater), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: '本当に削除しますか?' } %></p>
          </div>
      </div>

      <div class="row">
        <div class="col-6">
          <table class="table">
            <tbody>
            <tr>
              <th scope="col-2">住所</th>
              <td><%= @theater.address %></td>
            </tr>
            <tr>
              <th scope="col">アクセス</th>
              <td><%= @theater.access %></td>
            </tr>
            <tr>
              <th scope="col">駐車場</th>
              <td><%= @theater.parking %></td>
            </tr>
            <tr>
              <th scope="col">電話番号</th>
              <td><%= @theater.phone_number %></td>
            </tr>
            <tr>
              <th scope="col">URL</th>
              <td><%= link_to @theater.url %></td>
            </tr>
            </tbody>
          </table>
        </div>
        <div class="col-4 my-4">
          <p><%= attachment_image_tag @theater, :image, size: "270x190", fallback: "no_image.jpg" %></p>
          <div id="map"></div>
        </div>
      </div>
    <% if @theater.comments.count > 0 %>
      <h2 class="m-2">コメント</h2>
        <% @theater.comments.each do |comments| %>
          <table class="table">
           <tbody>
            <tr>
              <td>
              <%= comments.user.name %>
              </td>
              <td>
              <%= comments.created_at.strftime('%Y/%m/%d') %>
              </td>
              <td>
              <%= comments.comment %>
              </td>
              <td>
                <div class="relative-comment-evaluation">
                <span>評価：</span>
                <span id="star-rate-<%= comments.id %>"></span>
                <script>
                $('#star-rate-<%= comments.id %>').raty({
                size: 36,
                starOff: "<%= asset_path('star-off.png') %>",
                starOn: "<%= asset_path('star-on.png') %>",
                starHalf: "<%= asset_path('star-half.png') %>",
                half: true,
                readOnly: true,
                score: <%= comments.clean %>,
                });
                </script>
                <%= comments.clean %>
                </div>
              </td>
              <td>
                <div class="comment-delete">
                  <%= link_to "削除", theater_comment_path(comments.theater, comments), method: :delete, class:"btn btn-outline-danger" %>
                </div>
              </td>
            </tr>
           </tbody>
          </table>
        <% end %>
        <% else %>
        <h5 class="m-2">コメントはありません</h5>
        <% end %>
        </div>
      </div>
    </div>
  </div>

<script type="text/javascript">
function initMap() {
<%# latitude,longitudeから位置を特定 %>
    var test ={lat: <%= @theater.latitude %>, lng: <%= @theater.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15,
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @theater.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

 <%# Map上の指定した位置にピンを挿して表示する %>
    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }
</script>

<script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>
<%# 表示するmapのcss %>
<style type="text/css">
  #map { height: 200px;
         width: 100%;}
</style>